version: 1.0.{build}

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.2.5
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

environment:
  matrix:
  - TEST: CI
  - TEST: PLUGIN
    SQ_VERSION: DEV
  - TEST: PLUGIN
    SQ_VERSION: LTS
  - TEST: PLUGIN
    SQ_VERSION: LATEST_RELEASE

matrix:
  fast_finish: true

build_script:
  - ps: ./appveyor.ps1

test: off

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
